site_name: Gu铆a de Infraestructura Xen, Linux y contenedores
site_url: https://jacedoe.github.io/server-labs/
repo_url: https://github.com/jacedoe/server-labs
repo_name: server-labs
site_description: >
  Documentaci贸n paso a paso para el despliegue de VM con XCP-ng,
  contenedores Podman (NGINX, MariaDB, WordPress).

# ============================
#        TEMA Y ESTILO
# ============================
theme:
  name: readthedocs

# ============================
#    EXTENSIONES MARKDOWN
# ============================
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true

# ============================
#       ARCHIVOS EXTRA
# ============================
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jacedoe

# ============================
#      NAVEGACIN DEL SITIO
# ============================
nav:
  -  Inicio: index.md

  -  1. Preparaci贸n de la Infraestructura:
      - 1.1. Servidor XCP-ng: preparacion/instalacion_xo_lite.md
      - 1.2. Despliegue VM Alpine LInux: preparacion/instalacion_alpine.md

  -  2. Despliegue en producci贸n de sitio web:
      - 2.1. Intalaci贸n de Nginx y Hugo: web/nginx_conf.md
      - 2.2. Configuraci贸n del stack Nginx-MariaDB-WordPress: web/despliegue_stack_web.md
      - 2.3. Cloudflare Tunnel: seguridad/cloudflare_tunnel.md

  -  Ap茅ndices:
      - Comandos tiles: apendices/comandos_utiles.md

  -  Gu铆a de Estilo (Oficial): guia-de-estilo.md
